version: '3.9'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.13.3
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
      - "9300:9300"
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9200 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    image: python:3.10
    working_dir: /app
    volumes:
      - ./back:/app
    ports:
      - "5000:5000"

    command: >
      sh -c 'pip install poetry && poetry install && (echo "Waiting for Elasticsearch to be ready..." &&

        until curl -s http://elasticsearch:9200/_cluster/health | grep -q "\"status\":\"green\|yellow\""; do
            echo "Elasticsearch not ready yet, waiting...";
            sleep 5;
        done) && 
        
        echo "Elasticsearch is ready!"; 
        
        if [ "$seed" = "true" ]; then
            poetry run python -m src.seeder && poetry run python -m src;
        else
            poetry run python -m src;
        fi'
    depends_on:
      - elasticsearch
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:5000 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5

  frontend:
    image: node:16
    working_dir: /app
    volumes:
      - ./front:/app
    ports:
      - "3000:3000"
    command: sh -c "npm install && npm start"
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3000 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
